### ISSUE TITLE
the databases

### ISSUE THREAD

**Issue by lujiahui321** [bboylyg/Ensemble_CNN_Models_For_Classification#1]
Hello, I would like to ask the databases folder in each category are manually sorted validation set and test set? Or are all the photos of dogs under the dog folder?

**Comment by bboylyg** [comment]
the dogs in dog folder and the cats in cat folder

**Comment by lujiahui321** [comment]
Thank you very much. I have another question to ask you. In the votes, what if the results predicted by the two models are different?

**Comment by lujiahui321** [comment]
您好 ，预测输出结果是三个矩阵，一个是多数投票的 一个是简单平均的 ，那第一个是什么啊？

**Comment by bboylyg** [comment]
第一个是没有集成的第一个模型结果

**Comment by lujiahui321** [comment]
谢谢！ 那多数投票的时候 如果两个模型结果不同 是怎么取得啊？

**Comment by bboylyg** [comment]
如果相同这个逻辑我没有写进去，你可以自己添加个判断。如果相同，拒绝投票或者随机返回预测标签

**Comment by bboylyg** [comment]
你看下周志华的西瓜书，有一章讲集成学习，里面对不同投票分类方式作了介绍。
